# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import traffic_pb2 as traffic__pb2


class TrafficServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCameras = channel.unary_unary(
                '/greet.TrafficService/GetCameras',
                request_serializer=traffic__pb2.CamerasRequest.SerializeToString,
                response_deserializer=traffic__pb2.CamerasReply.FromString,
                )


class TrafficServiceServicer(object):
    """The greeting service definition.
    """

    def GetCameras(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrafficServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameras,
                    request_deserializer=traffic__pb2.CamerasRequest.FromString,
                    response_serializer=traffic__pb2.CamerasReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.TrafficService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrafficService(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.TrafficService/GetCameras',
            traffic__pb2.CamerasRequest.SerializeToString,
            traffic__pb2.CamerasReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
